server:
  port: 8080
  error:
    include-message: always

spring:
  data:
    mongodb:
      uri: mongodb://${MONGODB_URI:localhost:27017/test}

mongock:
  migration-scan-package:
  - com.example.alex90bar.productlist.config

