server:
  port: 8080
  error:
    include-message: always

spring:
  datasource:
    url: jdbc:${DATABASE_URL:postgresql://localhost:5432/productList}
    username: ${USER_DB:postgres}
    password: ${PASS_DB:postgres}
    driverClassName: org.postgresql.Driver


  sql:
    init:
      mode: never

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        format_sql: true
      open-in-view: false


  liquibase:
    change-log: classpath:db-productList-changelog.xml
    enabled: true



